// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: cms.proto

package cms

import (
	"context"

	"looklook/app/cms/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Article                     = pb.Article
	BatchCreateClearingDataReq  = pb.BatchCreateClearingDataReq
	BatchCreateClearingDataResp = pb.BatchCreateClearingDataResp
	ClearingData                = pb.ClearingData
	CreateArticleReq            = pb.CreateArticleReq
	CreateArticleResp           = pb.CreateArticleResp
	CreateClearingDataReq       = pb.CreateClearingDataReq
	CreateClearingDataResp      = pb.CreateClearingDataResp
	DeleteArticleReq            = pb.DeleteArticleReq
	DeleteArticleResp           = pb.DeleteArticleResp
	DeleteClearingDataReq       = pb.DeleteClearingDataReq
	DeleteClearingDataResp      = pb.DeleteClearingDataResp
	GetArticleDetailReq         = pb.GetArticleDetailReq
	GetArticleDetailResp        = pb.GetArticleDetailResp
	GetArticleListReq           = pb.GetArticleListReq
	GetArticleListResp          = pb.GetArticleListResp
	GetClearingDataDetailReq    = pb.GetClearingDataDetailReq
	GetClearingDataDetailResp   = pb.GetClearingDataDetailResp
	GetClearingDataListReq      = pb.GetClearingDataListReq
	GetClearingDataListResp     = pb.GetClearingDataListResp
	LikeArticleReq              = pb.LikeArticleReq
	LikeArticleResp             = pb.LikeArticleResp
	PublishArticleReq           = pb.PublishArticleReq
	PublishArticleResp          = pb.PublishArticleResp
	UpdateArticleReq            = pb.UpdateArticleReq
	UpdateArticleResp           = pb.UpdateArticleResp
	UpdateClearingDataReq       = pb.UpdateClearingDataReq
	UpdateClearingDataResp      = pb.UpdateClearingDataResp

	Cms interface {
		CreateArticle(ctx context.Context, in *CreateArticleReq, opts ...grpc.CallOption) (*CreateArticleResp, error)
		UpdateArticle(ctx context.Context, in *UpdateArticleReq, opts ...grpc.CallOption) (*UpdateArticleResp, error)
		PublishArticle(ctx context.Context, in *PublishArticleReq, opts ...grpc.CallOption) (*PublishArticleResp, error)
		GetArticleDetail(ctx context.Context, in *GetArticleDetailReq, opts ...grpc.CallOption) (*GetArticleDetailResp, error)
		GetArticleList(ctx context.Context, in *GetArticleListReq, opts ...grpc.CallOption) (*GetArticleListResp, error)
		LikeArticle(ctx context.Context, in *LikeArticleReq, opts ...grpc.CallOption) (*LikeArticleResp, error)
		DeleteArticle(ctx context.Context, in *DeleteArticleReq, opts ...grpc.CallOption) (*DeleteArticleResp, error)
		CreateClearingData(ctx context.Context, in *CreateClearingDataReq, opts ...grpc.CallOption) (*CreateClearingDataResp, error)
		UpdateClearingData(ctx context.Context, in *UpdateClearingDataReq, opts ...grpc.CallOption) (*UpdateClearingDataResp, error)
		GetClearingDataDetail(ctx context.Context, in *GetClearingDataDetailReq, opts ...grpc.CallOption) (*GetClearingDataDetailResp, error)
		GetClearingDataList(ctx context.Context, in *GetClearingDataListReq, opts ...grpc.CallOption) (*GetClearingDataListResp, error)
		DeleteClearingData(ctx context.Context, in *DeleteClearingDataReq, opts ...grpc.CallOption) (*DeleteClearingDataResp, error)
		BatchCreateClearingData(ctx context.Context, in *BatchCreateClearingDataReq, opts ...grpc.CallOption) (*BatchCreateClearingDataResp, error)
	}

	defaultCms struct {
		cli zrpc.Client
	}
)

func NewCms(cli zrpc.Client) Cms {
	return &defaultCms{
		cli: cli,
	}
}

func (m *defaultCms) CreateArticle(ctx context.Context, in *CreateArticleReq, opts ...grpc.CallOption) (*CreateArticleResp, error) {
	client := pb.NewCmsClient(m.cli.Conn())
	return client.CreateArticle(ctx, in, opts...)
}

func (m *defaultCms) UpdateArticle(ctx context.Context, in *UpdateArticleReq, opts ...grpc.CallOption) (*UpdateArticleResp, error) {
	client := pb.NewCmsClient(m.cli.Conn())
	return client.UpdateArticle(ctx, in, opts...)
}

func (m *defaultCms) PublishArticle(ctx context.Context, in *PublishArticleReq, opts ...grpc.CallOption) (*PublishArticleResp, error) {
	client := pb.NewCmsClient(m.cli.Conn())
	return client.PublishArticle(ctx, in, opts...)
}

func (m *defaultCms) GetArticleDetail(ctx context.Context, in *GetArticleDetailReq, opts ...grpc.CallOption) (*GetArticleDetailResp, error) {
	client := pb.NewCmsClient(m.cli.Conn())
	return client.GetArticleDetail(ctx, in, opts...)
}

func (m *defaultCms) GetArticleList(ctx context.Context, in *GetArticleListReq, opts ...grpc.CallOption) (*GetArticleListResp, error) {
	client := pb.NewCmsClient(m.cli.Conn())
	return client.GetArticleList(ctx, in, opts...)
}

func (m *defaultCms) LikeArticle(ctx context.Context, in *LikeArticleReq, opts ...grpc.CallOption) (*LikeArticleResp, error) {
	client := pb.NewCmsClient(m.cli.Conn())
	return client.LikeArticle(ctx, in, opts...)
}

func (m *defaultCms) DeleteArticle(ctx context.Context, in *DeleteArticleReq, opts ...grpc.CallOption) (*DeleteArticleResp, error) {
	client := pb.NewCmsClient(m.cli.Conn())
	return client.DeleteArticle(ctx, in, opts...)
}

func (m *defaultCms) CreateClearingData(ctx context.Context, in *CreateClearingDataReq, opts ...grpc.CallOption) (*CreateClearingDataResp, error) {
	client := pb.NewCmsClient(m.cli.Conn())
	return client.CreateClearingData(ctx, in, opts...)
}

func (m *defaultCms) UpdateClearingData(ctx context.Context, in *UpdateClearingDataReq, opts ...grpc.CallOption) (*UpdateClearingDataResp, error) {
	client := pb.NewCmsClient(m.cli.Conn())
	return client.UpdateClearingData(ctx, in, opts...)
}

func (m *defaultCms) GetClearingDataDetail(ctx context.Context, in *GetClearingDataDetailReq, opts ...grpc.CallOption) (*GetClearingDataDetailResp, error) {
	client := pb.NewCmsClient(m.cli.Conn())
	return client.GetClearingDataDetail(ctx, in, opts...)
}

func (m *defaultCms) GetClearingDataList(ctx context.Context, in *GetClearingDataListReq, opts ...grpc.CallOption) (*GetClearingDataListResp, error) {
	client := pb.NewCmsClient(m.cli.Conn())
	return client.GetClearingDataList(ctx, in, opts...)
}

func (m *defaultCms) DeleteClearingData(ctx context.Context, in *DeleteClearingDataReq, opts ...grpc.CallOption) (*DeleteClearingDataResp, error) {
	client := pb.NewCmsClient(m.cli.Conn())
	return client.DeleteClearingData(ctx, in, opts...)
}

func (m *defaultCms) BatchCreateClearingData(ctx context.Context, in *BatchCreateClearingDataReq, opts ...grpc.CallOption) (*BatchCreateClearingDataResp, error) {
	client := pb.NewCmsClient(m.cli.Conn())
	return client.BatchCreateClearingData(ctx, in, opts...)
}
