// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: cms.proto

package cms

import (
	"context"

	"looklook/app/cms/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Article              = pb.Article
	CreateArticleReq     = pb.CreateArticleReq
	CreateArticleResp    = pb.CreateArticleResp
	DeleteArticleReq     = pb.DeleteArticleReq
	DeleteArticleResp    = pb.DeleteArticleResp
	GetArticleDetailReq  = pb.GetArticleDetailReq
	GetArticleDetailResp = pb.GetArticleDetailResp
	GetArticleListReq    = pb.GetArticleListReq
	GetArticleListResp   = pb.GetArticleListResp
	LikeArticleReq       = pb.LikeArticleReq
	LikeArticleResp      = pb.LikeArticleResp
	PublishArticleReq    = pb.PublishArticleReq
	PublishArticleResp   = pb.PublishArticleResp
	UpdateArticleReq     = pb.UpdateArticleReq
	UpdateArticleResp    = pb.UpdateArticleResp

	Cms interface {
		CreateArticle(ctx context.Context, in *CreateArticleReq, opts ...grpc.CallOption) (*CreateArticleResp, error)
		UpdateArticle(ctx context.Context, in *UpdateArticleReq, opts ...grpc.CallOption) (*UpdateArticleResp, error)
		PublishArticle(ctx context.Context, in *PublishArticleReq, opts ...grpc.CallOption) (*PublishArticleResp, error)
		GetArticleDetail(ctx context.Context, in *GetArticleDetailReq, opts ...grpc.CallOption) (*GetArticleDetailResp, error)
		GetArticleList(ctx context.Context, in *GetArticleListReq, opts ...grpc.CallOption) (*GetArticleListResp, error)
		LikeArticle(ctx context.Context, in *LikeArticleReq, opts ...grpc.CallOption) (*LikeArticleResp, error)
		DeleteArticle(ctx context.Context, in *DeleteArticleReq, opts ...grpc.CallOption) (*DeleteArticleResp, error)
	}

	defaultCms struct {
		cli zrpc.Client
	}
)

func NewCms(cli zrpc.Client) Cms {
	return &defaultCms{
		cli: cli,
	}
}

func (m *defaultCms) CreateArticle(ctx context.Context, in *CreateArticleReq, opts ...grpc.CallOption) (*CreateArticleResp, error) {
	client := pb.NewCmsClient(m.cli.Conn())
	return client.CreateArticle(ctx, in, opts...)
}

func (m *defaultCms) UpdateArticle(ctx context.Context, in *UpdateArticleReq, opts ...grpc.CallOption) (*UpdateArticleResp, error) {
	client := pb.NewCmsClient(m.cli.Conn())
	return client.UpdateArticle(ctx, in, opts...)
}

func (m *defaultCms) PublishArticle(ctx context.Context, in *PublishArticleReq, opts ...grpc.CallOption) (*PublishArticleResp, error) {
	client := pb.NewCmsClient(m.cli.Conn())
	return client.PublishArticle(ctx, in, opts...)
}

func (m *defaultCms) GetArticleDetail(ctx context.Context, in *GetArticleDetailReq, opts ...grpc.CallOption) (*GetArticleDetailResp, error) {
	client := pb.NewCmsClient(m.cli.Conn())
	return client.GetArticleDetail(ctx, in, opts...)
}

func (m *defaultCms) GetArticleList(ctx context.Context, in *GetArticleListReq, opts ...grpc.CallOption) (*GetArticleListResp, error) {
	client := pb.NewCmsClient(m.cli.Conn())
	return client.GetArticleList(ctx, in, opts...)
}

func (m *defaultCms) LikeArticle(ctx context.Context, in *LikeArticleReq, opts ...grpc.CallOption) (*LikeArticleResp, error) {
	client := pb.NewCmsClient(m.cli.Conn())
	return client.LikeArticle(ctx, in, opts...)
}

func (m *defaultCms) DeleteArticle(ctx context.Context, in *DeleteArticleReq, opts ...grpc.CallOption) (*DeleteArticleResp, error) {
	client := pb.NewCmsClient(m.cli.Conn())
	return client.DeleteArticle(ctx, in, opts...)
}
