// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: cms.proto

package server

import (
	"context"

	"looklook/app/cms/cmd/rpc/internal/logic"
	"looklook/app/cms/cmd/rpc/internal/svc"
	"looklook/app/cms/cmd/rpc/pb"
)

type CmsServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedCmsServer
}

func NewCmsServer(svcCtx *svc.ServiceContext) *CmsServer {
	return &CmsServer{
		svcCtx: svcCtx,
	}
}

func (s *CmsServer) CreateArticle(ctx context.Context, in *pb.CreateArticleReq) (*pb.CreateArticleResp, error) {
	l := logic.NewCreateArticleLogic(ctx, s.svcCtx)
	return l.CreateArticle(in)
}

func (s *CmsServer) UpdateArticle(ctx context.Context, in *pb.UpdateArticleReq) (*pb.UpdateArticleResp, error) {
	l := logic.NewUpdateArticleLogic(ctx, s.svcCtx)
	return l.UpdateArticle(in)
}

func (s *CmsServer) PublishArticle(ctx context.Context, in *pb.PublishArticleReq) (*pb.PublishArticleResp, error) {
	l := logic.NewPublishArticleLogic(ctx, s.svcCtx)
	return l.PublishArticle(in)
}

func (s *CmsServer) GetArticleDetail(ctx context.Context, in *pb.GetArticleDetailReq) (*pb.GetArticleDetailResp, error) {
	l := logic.NewGetArticleDetailLogic(ctx, s.svcCtx)
	return l.GetArticleDetail(in)
}

func (s *CmsServer) GetArticleList(ctx context.Context, in *pb.GetArticleListReq) (*pb.GetArticleListResp, error) {
	l := logic.NewGetArticleListLogic(ctx, s.svcCtx)
	return l.GetArticleList(in)
}

func (s *CmsServer) LikeArticle(ctx context.Context, in *pb.LikeArticleReq) (*pb.LikeArticleResp, error) {
	l := logic.NewLikeArticleLogic(ctx, s.svcCtx)
	return l.LikeArticle(in)
}

func (s *CmsServer) DeleteArticle(ctx context.Context, in *pb.DeleteArticleReq) (*pb.DeleteArticleResp, error) {
	l := logic.NewDeleteArticleLogic(ctx, s.svcCtx)
	return l.DeleteArticle(in)
}

func (s *CmsServer) CreateClearingData(ctx context.Context, in *pb.CreateClearingDataReq) (*pb.CreateClearingDataResp, error) {
	l := logic.NewCreateClearingDataLogic(ctx, s.svcCtx)
	return l.CreateClearingData(in)
}

func (s *CmsServer) UpdateClearingData(ctx context.Context, in *pb.UpdateClearingDataReq) (*pb.UpdateClearingDataResp, error) {
	l := logic.NewUpdateClearingDataLogic(ctx, s.svcCtx)
	return l.UpdateClearingData(in)
}

func (s *CmsServer) GetClearingDataDetail(ctx context.Context, in *pb.GetClearingDataDetailReq) (*pb.GetClearingDataDetailResp, error) {
	l := logic.NewGetClearingDataDetailLogic(ctx, s.svcCtx)
	return l.GetClearingDataDetail(in)
}

func (s *CmsServer) GetClearingDataList(ctx context.Context, in *pb.GetClearingDataListReq) (*pb.GetClearingDataListResp, error) {
	l := logic.NewGetClearingDataListLogic(ctx, s.svcCtx)
	return l.GetClearingDataList(in)
}

func (s *CmsServer) DeleteClearingData(ctx context.Context, in *pb.DeleteClearingDataReq) (*pb.DeleteClearingDataResp, error) {
	l := logic.NewDeleteClearingDataLogic(ctx, s.svcCtx)
	return l.DeleteClearingData(in)
}

func (s *CmsServer) BatchCreateClearingData(ctx context.Context, in *pb.BatchCreateClearingDataReq) (*pb.BatchCreateClearingDataResp, error) {
	l := logic.NewBatchCreateClearingDataLogic(ctx, s.svcCtx)
	return l.BatchCreateClearingData(in)
}
