// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: cms.proto

package server

import (
	"context"

	"looklook/app/cms/cmd/rpc/internal/logic"
	"looklook/app/cms/cmd/rpc/internal/svc"
	"looklook/app/cms/cmd/rpc/pb"
)

type CmsServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedCmsServer
}

func NewCmsServer(svcCtx *svc.ServiceContext) *CmsServer {
	return &CmsServer{
		svcCtx: svcCtx,
	}
}

func (s *CmsServer) CreateArticle(ctx context.Context, in *pb.CreateArticleReq) (*pb.CreateArticleResp, error) {
	l := logic.NewCreateArticleLogic(ctx, s.svcCtx)
	return l.CreateArticle(in)
}

func (s *CmsServer) UpdateArticle(ctx context.Context, in *pb.UpdateArticleReq) (*pb.UpdateArticleResp, error) {
	l := logic.NewUpdateArticleLogic(ctx, s.svcCtx)
	return l.UpdateArticle(in)
}

func (s *CmsServer) PublishArticle(ctx context.Context, in *pb.PublishArticleReq) (*pb.PublishArticleResp, error) {
	l := logic.NewPublishArticleLogic(ctx, s.svcCtx)
	return l.PublishArticle(in)
}

func (s *CmsServer) GetArticleDetail(ctx context.Context, in *pb.GetArticleDetailReq) (*pb.GetArticleDetailResp, error) {
	l := logic.NewGetArticleDetailLogic(ctx, s.svcCtx)
	return l.GetArticleDetail(in)
}

func (s *CmsServer) GetArticleList(ctx context.Context, in *pb.GetArticleListReq) (*pb.GetArticleListResp, error) {
	l := logic.NewGetArticleListLogic(ctx, s.svcCtx)
	return l.GetArticleList(in)
}

func (s *CmsServer) LikeArticle(ctx context.Context, in *pb.LikeArticleReq) (*pb.LikeArticleResp, error) {
	l := logic.NewLikeArticleLogic(ctx, s.svcCtx)
	return l.LikeArticle(in)
}

func (s *CmsServer) DeleteArticle(ctx context.Context, in *pb.DeleteArticleReq) (*pb.DeleteArticleResp, error) {
	l := logic.NewDeleteArticleLogic(ctx, s.svcCtx)
	return l.DeleteArticle(in)
}
