// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type Article struct {
	Id          int64  `json:"id"`
	Title       string `json:"title"`
	Content     string `json:"content"`
	PublishTime string `json:"publishTime"`
	Category    string `json:"category"`
	LikeCount   int64  `json:"likeCount"`
	AuthorId    int64  `json:"authorId"`
	CoverImage  string `json:"coverImage"`
	Status      int64  `json:"status"`
}

type ArticleDetailReq struct {
	Id int64 `json:"id"`
}

type ArticleDetailResp struct {
	Article Article `json:"article"`
}

type ArticleListReq struct {
	Category string `json:"category,optional"`
	Page     int64  `json:"page,default=1"`
	PageSize int64  `json:"pageSize,default=10"`
}

type ArticleListResp struct {
	List  []Article `json:"list"`
	Total int64     `json:"total"`
}

type CreateArticleReq struct {
	Title      string `json:"title"`
	Content    string `json:"content"`
	Category   string `json:"category"`
	CoverImage string `json:"coverImage,optional"`
}

type CreateArticleResp struct {
	Id int64 `json:"id"`
}

type DeleteArticleReq struct {
	Id int64 `json:"id"`
}

type DeleteArticleResp struct {
	Success bool `json:"success"`
}

type LikeArticleReq struct {
	Id int64 `json:"id"`
}

type LikeArticleResp struct {
	LikeCount int64 `json:"likeCount"`
}

type PublishArticleReq struct {
	Id int64 `json:"id"`
}

type PublishArticleResp struct {
	Success bool `json:"success"`
}

type UpdateArticleReq struct {
	Id         int64  `json:"id"`
	Title      string `json:"title,optional"`
	Content    string `json:"content,optional"`
	Category   string `json:"category,optional"`
	CoverImage string `json:"coverImage,optional"`
}

type UpdateArticleResp struct {
	Success bool `json:"success"`
}
