// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: cms.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// model
type Article struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content"`
	PublishTime   string                 `protobuf:"bytes,4,opt,name=publishTime,proto3" json:"publishTime"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category"`
	LikeCount     int64                  `protobuf:"varint,6,opt,name=likeCount,proto3" json:"likeCount"`
	AuthorId      int64                  `protobuf:"varint,7,opt,name=authorId,proto3" json:"authorId"`
	CoverImage    string                 `protobuf:"bytes,8,opt,name=coverImage,proto3" json:"coverImage"`
	Status        int64                  `protobuf:"varint,9,opt,name=status,proto3" json:"status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_cms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_cms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_cms_proto_rawDescGZIP(), []int{0}
}

func (x *Article) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Article) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Article) GetPublishTime() string {
	if x != nil {
		return x.PublishTime
	}
	return ""
}

func (x *Article) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Article) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Article) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *Article) GetCoverImage() string {
	if x != nil {
		return x.CoverImage
	}
	return ""
}

func (x *Article) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

// req 、resp
type CreateArticleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category"`
	AuthorId      int64                  `protobuf:"varint,4,opt,name=authorId,proto3" json:"authorId"`
	CoverImage    string                 `protobuf:"bytes,5,opt,name=coverImage,proto3" json:"coverImage"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleReq) Reset() {
	*x = CreateArticleReq{}
	mi := &file_cms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleReq) ProtoMessage() {}

func (x *CreateArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_cms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleReq.ProtoReflect.Descriptor instead.
func (*CreateArticleReq) Descriptor() ([]byte, []int) {
	return file_cms_proto_rawDescGZIP(), []int{1}
}

func (x *CreateArticleReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateArticleReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateArticleReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateArticleReq) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *CreateArticleReq) GetCoverImage() string {
	if x != nil {
		return x.CoverImage
	}
	return ""
}

type CreateArticleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleResp) Reset() {
	*x = CreateArticleResp{}
	mi := &file_cms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleResp) ProtoMessage() {}

func (x *CreateArticleResp) ProtoReflect() protoreflect.Message {
	mi := &file_cms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleResp.ProtoReflect.Descriptor instead.
func (*CreateArticleResp) Descriptor() ([]byte, []int) {
	return file_cms_proto_rawDescGZIP(), []int{2}
}

func (x *CreateArticleResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateArticleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category"`
	CoverImage    string                 `protobuf:"bytes,5,opt,name=coverImage,proto3" json:"coverImage"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleReq) Reset() {
	*x = UpdateArticleReq{}
	mi := &file_cms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleReq) ProtoMessage() {}

func (x *UpdateArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_cms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleReq.ProtoReflect.Descriptor instead.
func (*UpdateArticleReq) Descriptor() ([]byte, []int) {
	return file_cms_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateArticleReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateArticleReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateArticleReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateArticleReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateArticleReq) GetCoverImage() string {
	if x != nil {
		return x.CoverImage
	}
	return ""
}

type UpdateArticleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleResp) Reset() {
	*x = UpdateArticleResp{}
	mi := &file_cms_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleResp) ProtoMessage() {}

func (x *UpdateArticleResp) ProtoReflect() protoreflect.Message {
	mi := &file_cms_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleResp.ProtoReflect.Descriptor instead.
func (*UpdateArticleResp) Descriptor() ([]byte, []int) {
	return file_cms_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateArticleResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PublishArticleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	AuthorId      int64                  `protobuf:"varint,2,opt,name=authorId,proto3" json:"authorId"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishArticleReq) Reset() {
	*x = PublishArticleReq{}
	mi := &file_cms_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishArticleReq) ProtoMessage() {}

func (x *PublishArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_cms_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishArticleReq.ProtoReflect.Descriptor instead.
func (*PublishArticleReq) Descriptor() ([]byte, []int) {
	return file_cms_proto_rawDescGZIP(), []int{5}
}

func (x *PublishArticleReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PublishArticleReq) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

type PublishArticleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishArticleResp) Reset() {
	*x = PublishArticleResp{}
	mi := &file_cms_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishArticleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishArticleResp) ProtoMessage() {}

func (x *PublishArticleResp) ProtoReflect() protoreflect.Message {
	mi := &file_cms_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishArticleResp.ProtoReflect.Descriptor instead.
func (*PublishArticleResp) Descriptor() ([]byte, []int) {
	return file_cms_proto_rawDescGZIP(), []int{6}
}

func (x *PublishArticleResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetArticleDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleDetailReq) Reset() {
	*x = GetArticleDetailReq{}
	mi := &file_cms_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleDetailReq) ProtoMessage() {}

func (x *GetArticleDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_cms_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleDetailReq.ProtoReflect.Descriptor instead.
func (*GetArticleDetailReq) Descriptor() ([]byte, []int) {
	return file_cms_proto_rawDescGZIP(), []int{7}
}

func (x *GetArticleDetailReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetArticleDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article,proto3" json:"article"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleDetailResp) Reset() {
	*x = GetArticleDetailResp{}
	mi := &file_cms_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleDetailResp) ProtoMessage() {}

func (x *GetArticleDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_cms_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleDetailResp.ProtoReflect.Descriptor instead.
func (*GetArticleDetailResp) Descriptor() ([]byte, []int) {
	return file_cms_proto_rawDescGZIP(), []int{8}
}

func (x *GetArticleDetailResp) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type GetArticleListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleListReq) Reset() {
	*x = GetArticleListReq{}
	mi := &file_cms_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleListReq) ProtoMessage() {}

func (x *GetArticleListReq) ProtoReflect() protoreflect.Message {
	mi := &file_cms_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleListReq.ProtoReflect.Descriptor instead.
func (*GetArticleListReq) Descriptor() ([]byte, []int) {
	return file_cms_proto_rawDescGZIP(), []int{9}
}

func (x *GetArticleListReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GetArticleListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetArticleListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetArticleListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Article             `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleListResp) Reset() {
	*x = GetArticleListResp{}
	mi := &file_cms_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleListResp) ProtoMessage() {}

func (x *GetArticleListResp) ProtoReflect() protoreflect.Message {
	mi := &file_cms_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleListResp.ProtoReflect.Descriptor instead.
func (*GetArticleListResp) Descriptor() ([]byte, []int) {
	return file_cms_proto_rawDescGZIP(), []int{10}
}

func (x *GetArticleListResp) GetList() []*Article {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetArticleListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type LikeArticleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeArticleReq) Reset() {
	*x = LikeArticleReq{}
	mi := &file_cms_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeArticleReq) ProtoMessage() {}

func (x *LikeArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_cms_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeArticleReq.ProtoReflect.Descriptor instead.
func (*LikeArticleReq) Descriptor() ([]byte, []int) {
	return file_cms_proto_rawDescGZIP(), []int{11}
}

func (x *LikeArticleReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type LikeArticleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LikeCount     int64                  `protobuf:"varint,1,opt,name=likeCount,proto3" json:"likeCount"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeArticleResp) Reset() {
	*x = LikeArticleResp{}
	mi := &file_cms_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeArticleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeArticleResp) ProtoMessage() {}

func (x *LikeArticleResp) ProtoReflect() protoreflect.Message {
	mi := &file_cms_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeArticleResp.ProtoReflect.Descriptor instead.
func (*LikeArticleResp) Descriptor() ([]byte, []int) {
	return file_cms_proto_rawDescGZIP(), []int{12}
}

func (x *LikeArticleResp) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

type DeleteArticleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	AuthorId      int64                  `protobuf:"varint,2,opt,name=authorId,proto3" json:"authorId"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleReq) Reset() {
	*x = DeleteArticleReq{}
	mi := &file_cms_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleReq) ProtoMessage() {}

func (x *DeleteArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_cms_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleReq.ProtoReflect.Descriptor instead.
func (*DeleteArticleReq) Descriptor() ([]byte, []int) {
	return file_cms_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteArticleReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteArticleReq) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

type DeleteArticleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleResp) Reset() {
	*x = DeleteArticleResp{}
	mi := &file_cms_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleResp) ProtoMessage() {}

func (x *DeleteArticleResp) ProtoReflect() protoreflect.Message {
	mi := &file_cms_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleResp.ProtoReflect.Descriptor instead.
func (*DeleteArticleResp) Descriptor() ([]byte, []int) {
	return file_cms_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteArticleResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_cms_proto protoreflect.FileDescriptor

const file_cms_proto_rawDesc = "" +
	"\n" +
	"\tcms.proto\x12\x02pb\"\xf9\x01\n" +
	"\aArticle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12 \n" +
	"\vpublishTime\x18\x04 \x01(\tR\vpublishTime\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x1c\n" +
	"\tlikeCount\x18\x06 \x01(\x03R\tlikeCount\x12\x1a\n" +
	"\bauthorId\x18\a \x01(\x03R\bauthorId\x12\x1e\n" +
	"\n" +
	"coverImage\x18\b \x01(\tR\n" +
	"coverImage\x12\x16\n" +
	"\x06status\x18\t \x01(\x03R\x06status\"\x9a\x01\n" +
	"\x10CreateArticleReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x1a\n" +
	"\bauthorId\x18\x04 \x01(\x03R\bauthorId\x12\x1e\n" +
	"\n" +
	"coverImage\x18\x05 \x01(\tR\n" +
	"coverImage\"#\n" +
	"\x11CreateArticleResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x8e\x01\n" +
	"\x10UpdateArticleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x1e\n" +
	"\n" +
	"coverImage\x18\x05 \x01(\tR\n" +
	"coverImage\"-\n" +
	"\x11UpdateArticleResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"?\n" +
	"\x11PublishArticleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bauthorId\x18\x02 \x01(\x03R\bauthorId\".\n" +
	"\x12PublishArticleResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"%\n" +
	"\x13GetArticleDetailReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"=\n" +
	"\x14GetArticleDetailResp\x12%\n" +
	"\aarticle\x18\x01 \x01(\v2\v.pb.ArticleR\aarticle\"_\n" +
	"\x11GetArticleListReq\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x03R\bpageSize\"K\n" +
	"\x12GetArticleListResp\x12\x1f\n" +
	"\x04list\x18\x01 \x03(\v2\v.pb.ArticleR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\" \n" +
	"\x0eLikeArticleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"/\n" +
	"\x0fLikeArticleResp\x12\x1c\n" +
	"\tlikeCount\x18\x01 \x01(\x03R\tlikeCount\">\n" +
	"\x10DeleteArticleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bauthorId\x18\x02 \x01(\x03R\bauthorId\"-\n" +
	"\x11DeleteArticleResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xc0\x03\n" +
	"\x03cms\x12<\n" +
	"\rcreateArticle\x12\x14.pb.CreateArticleReq\x1a\x15.pb.CreateArticleResp\x12<\n" +
	"\rupdateArticle\x12\x14.pb.UpdateArticleReq\x1a\x15.pb.UpdateArticleResp\x12?\n" +
	"\x0epublishArticle\x12\x15.pb.PublishArticleReq\x1a\x16.pb.PublishArticleResp\x12E\n" +
	"\x10getArticleDetail\x12\x17.pb.GetArticleDetailReq\x1a\x18.pb.GetArticleDetailResp\x12?\n" +
	"\x0egetArticleList\x12\x15.pb.GetArticleListReq\x1a\x16.pb.GetArticleListResp\x126\n" +
	"\vlikeArticle\x12\x12.pb.LikeArticleReq\x1a\x13.pb.LikeArticleResp\x12<\n" +
	"\rdeleteArticle\x12\x14.pb.DeleteArticleReq\x1a\x15.pb.DeleteArticleRespB\x06Z\x04./pbb\x06proto3"

var (
	file_cms_proto_rawDescOnce sync.Once
	file_cms_proto_rawDescData []byte
)

func file_cms_proto_rawDescGZIP() []byte {
	file_cms_proto_rawDescOnce.Do(func() {
		file_cms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cms_proto_rawDesc), len(file_cms_proto_rawDesc)))
	})
	return file_cms_proto_rawDescData
}

var file_cms_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_cms_proto_goTypes = []any{
	(*Article)(nil),              // 0: pb.Article
	(*CreateArticleReq)(nil),     // 1: pb.CreateArticleReq
	(*CreateArticleResp)(nil),    // 2: pb.CreateArticleResp
	(*UpdateArticleReq)(nil),     // 3: pb.UpdateArticleReq
	(*UpdateArticleResp)(nil),    // 4: pb.UpdateArticleResp
	(*PublishArticleReq)(nil),    // 5: pb.PublishArticleReq
	(*PublishArticleResp)(nil),   // 6: pb.PublishArticleResp
	(*GetArticleDetailReq)(nil),  // 7: pb.GetArticleDetailReq
	(*GetArticleDetailResp)(nil), // 8: pb.GetArticleDetailResp
	(*GetArticleListReq)(nil),    // 9: pb.GetArticleListReq
	(*GetArticleListResp)(nil),   // 10: pb.GetArticleListResp
	(*LikeArticleReq)(nil),       // 11: pb.LikeArticleReq
	(*LikeArticleResp)(nil),      // 12: pb.LikeArticleResp
	(*DeleteArticleReq)(nil),     // 13: pb.DeleteArticleReq
	(*DeleteArticleResp)(nil),    // 14: pb.DeleteArticleResp
}
var file_cms_proto_depIdxs = []int32{
	0,  // 0: pb.GetArticleDetailResp.article:type_name -> pb.Article
	0,  // 1: pb.GetArticleListResp.list:type_name -> pb.Article
	1,  // 2: pb.cms.createArticle:input_type -> pb.CreateArticleReq
	3,  // 3: pb.cms.updateArticle:input_type -> pb.UpdateArticleReq
	5,  // 4: pb.cms.publishArticle:input_type -> pb.PublishArticleReq
	7,  // 5: pb.cms.getArticleDetail:input_type -> pb.GetArticleDetailReq
	9,  // 6: pb.cms.getArticleList:input_type -> pb.GetArticleListReq
	11, // 7: pb.cms.likeArticle:input_type -> pb.LikeArticleReq
	13, // 8: pb.cms.deleteArticle:input_type -> pb.DeleteArticleReq
	2,  // 9: pb.cms.createArticle:output_type -> pb.CreateArticleResp
	4,  // 10: pb.cms.updateArticle:output_type -> pb.UpdateArticleResp
	6,  // 11: pb.cms.publishArticle:output_type -> pb.PublishArticleResp
	8,  // 12: pb.cms.getArticleDetail:output_type -> pb.GetArticleDetailResp
	10, // 13: pb.cms.getArticleList:output_type -> pb.GetArticleListResp
	12, // 14: pb.cms.likeArticle:output_type -> pb.LikeArticleResp
	14, // 15: pb.cms.deleteArticle:output_type -> pb.DeleteArticleResp
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_cms_proto_init() }
func file_cms_proto_init() {
	if File_cms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cms_proto_rawDesc), len(file_cms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cms_proto_goTypes,
		DependencyIndexes: file_cms_proto_depIdxs,
		MessageInfos:      file_cms_proto_msgTypes,
	}.Build()
	File_cms_proto = out.File
	file_cms_proto_goTypes = nil
	file_cms_proto_depIdxs = nil
}
