// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.3
// source: cms.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Cms_CreateArticle_FullMethodName           = "/pb.cms/createArticle"
	Cms_UpdateArticle_FullMethodName           = "/pb.cms/updateArticle"
	Cms_PublishArticle_FullMethodName          = "/pb.cms/publishArticle"
	Cms_GetArticleDetail_FullMethodName        = "/pb.cms/getArticleDetail"
	Cms_GetArticleList_FullMethodName          = "/pb.cms/getArticleList"
	Cms_LikeArticle_FullMethodName             = "/pb.cms/likeArticle"
	Cms_DeleteArticle_FullMethodName           = "/pb.cms/deleteArticle"
	Cms_CreateClearingData_FullMethodName      = "/pb.cms/createClearingData"
	Cms_UpdateClearingData_FullMethodName      = "/pb.cms/updateClearingData"
	Cms_GetClearingDataDetail_FullMethodName   = "/pb.cms/getClearingDataDetail"
	Cms_GetClearingDataList_FullMethodName     = "/pb.cms/getClearingDataList"
	Cms_DeleteClearingData_FullMethodName      = "/pb.cms/deleteClearingData"
	Cms_BatchCreateClearingData_FullMethodName = "/pb.cms/batchCreateClearingData"
)

// CmsClient is the client API for Cms service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// service
type CmsClient interface {
	CreateArticle(ctx context.Context, in *CreateArticleReq, opts ...grpc.CallOption) (*CreateArticleResp, error)
	UpdateArticle(ctx context.Context, in *UpdateArticleReq, opts ...grpc.CallOption) (*UpdateArticleResp, error)
	PublishArticle(ctx context.Context, in *PublishArticleReq, opts ...grpc.CallOption) (*PublishArticleResp, error)
	GetArticleDetail(ctx context.Context, in *GetArticleDetailReq, opts ...grpc.CallOption) (*GetArticleDetailResp, error)
	GetArticleList(ctx context.Context, in *GetArticleListReq, opts ...grpc.CallOption) (*GetArticleListResp, error)
	LikeArticle(ctx context.Context, in *LikeArticleReq, opts ...grpc.CallOption) (*LikeArticleResp, error)
	DeleteArticle(ctx context.Context, in *DeleteArticleReq, opts ...grpc.CallOption) (*DeleteArticleResp, error)
	CreateClearingData(ctx context.Context, in *CreateClearingDataReq, opts ...grpc.CallOption) (*CreateClearingDataResp, error)
	UpdateClearingData(ctx context.Context, in *UpdateClearingDataReq, opts ...grpc.CallOption) (*UpdateClearingDataResp, error)
	GetClearingDataDetail(ctx context.Context, in *GetClearingDataDetailReq, opts ...grpc.CallOption) (*GetClearingDataDetailResp, error)
	GetClearingDataList(ctx context.Context, in *GetClearingDataListReq, opts ...grpc.CallOption) (*GetClearingDataListResp, error)
	DeleteClearingData(ctx context.Context, in *DeleteClearingDataReq, opts ...grpc.CallOption) (*DeleteClearingDataResp, error)
	BatchCreateClearingData(ctx context.Context, in *BatchCreateClearingDataReq, opts ...grpc.CallOption) (*BatchCreateClearingDataResp, error)
}

type cmsClient struct {
	cc grpc.ClientConnInterface
}

func NewCmsClient(cc grpc.ClientConnInterface) CmsClient {
	return &cmsClient{cc}
}

func (c *cmsClient) CreateArticle(ctx context.Context, in *CreateArticleReq, opts ...grpc.CallOption) (*CreateArticleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateArticleResp)
	err := c.cc.Invoke(ctx, Cms_CreateArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) UpdateArticle(ctx context.Context, in *UpdateArticleReq, opts ...grpc.CallOption) (*UpdateArticleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateArticleResp)
	err := c.cc.Invoke(ctx, Cms_UpdateArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) PublishArticle(ctx context.Context, in *PublishArticleReq, opts ...grpc.CallOption) (*PublishArticleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishArticleResp)
	err := c.cc.Invoke(ctx, Cms_PublishArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) GetArticleDetail(ctx context.Context, in *GetArticleDetailReq, opts ...grpc.CallOption) (*GetArticleDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArticleDetailResp)
	err := c.cc.Invoke(ctx, Cms_GetArticleDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) GetArticleList(ctx context.Context, in *GetArticleListReq, opts ...grpc.CallOption) (*GetArticleListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArticleListResp)
	err := c.cc.Invoke(ctx, Cms_GetArticleList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) LikeArticle(ctx context.Context, in *LikeArticleReq, opts ...grpc.CallOption) (*LikeArticleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikeArticleResp)
	err := c.cc.Invoke(ctx, Cms_LikeArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) DeleteArticle(ctx context.Context, in *DeleteArticleReq, opts ...grpc.CallOption) (*DeleteArticleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteArticleResp)
	err := c.cc.Invoke(ctx, Cms_DeleteArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) CreateClearingData(ctx context.Context, in *CreateClearingDataReq, opts ...grpc.CallOption) (*CreateClearingDataResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateClearingDataResp)
	err := c.cc.Invoke(ctx, Cms_CreateClearingData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) UpdateClearingData(ctx context.Context, in *UpdateClearingDataReq, opts ...grpc.CallOption) (*UpdateClearingDataResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateClearingDataResp)
	err := c.cc.Invoke(ctx, Cms_UpdateClearingData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) GetClearingDataDetail(ctx context.Context, in *GetClearingDataDetailReq, opts ...grpc.CallOption) (*GetClearingDataDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClearingDataDetailResp)
	err := c.cc.Invoke(ctx, Cms_GetClearingDataDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) GetClearingDataList(ctx context.Context, in *GetClearingDataListReq, opts ...grpc.CallOption) (*GetClearingDataListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClearingDataListResp)
	err := c.cc.Invoke(ctx, Cms_GetClearingDataList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) DeleteClearingData(ctx context.Context, in *DeleteClearingDataReq, opts ...grpc.CallOption) (*DeleteClearingDataResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteClearingDataResp)
	err := c.cc.Invoke(ctx, Cms_DeleteClearingData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) BatchCreateClearingData(ctx context.Context, in *BatchCreateClearingDataReq, opts ...grpc.CallOption) (*BatchCreateClearingDataResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchCreateClearingDataResp)
	err := c.cc.Invoke(ctx, Cms_BatchCreateClearingData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CmsServer is the server API for Cms service.
// All implementations must embed UnimplementedCmsServer
// for forward compatibility.
//
// service
type CmsServer interface {
	CreateArticle(context.Context, *CreateArticleReq) (*CreateArticleResp, error)
	UpdateArticle(context.Context, *UpdateArticleReq) (*UpdateArticleResp, error)
	PublishArticle(context.Context, *PublishArticleReq) (*PublishArticleResp, error)
	GetArticleDetail(context.Context, *GetArticleDetailReq) (*GetArticleDetailResp, error)
	GetArticleList(context.Context, *GetArticleListReq) (*GetArticleListResp, error)
	LikeArticle(context.Context, *LikeArticleReq) (*LikeArticleResp, error)
	DeleteArticle(context.Context, *DeleteArticleReq) (*DeleteArticleResp, error)
	CreateClearingData(context.Context, *CreateClearingDataReq) (*CreateClearingDataResp, error)
	UpdateClearingData(context.Context, *UpdateClearingDataReq) (*UpdateClearingDataResp, error)
	GetClearingDataDetail(context.Context, *GetClearingDataDetailReq) (*GetClearingDataDetailResp, error)
	GetClearingDataList(context.Context, *GetClearingDataListReq) (*GetClearingDataListResp, error)
	DeleteClearingData(context.Context, *DeleteClearingDataReq) (*DeleteClearingDataResp, error)
	BatchCreateClearingData(context.Context, *BatchCreateClearingDataReq) (*BatchCreateClearingDataResp, error)
	mustEmbedUnimplementedCmsServer()
}

// UnimplementedCmsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCmsServer struct{}

func (UnimplementedCmsServer) CreateArticle(context.Context, *CreateArticleReq) (*CreateArticleResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateArticle not implemented")
}
func (UnimplementedCmsServer) UpdateArticle(context.Context, *UpdateArticleReq) (*UpdateArticleResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateArticle not implemented")
}
func (UnimplementedCmsServer) PublishArticle(context.Context, *PublishArticleReq) (*PublishArticleResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishArticle not implemented")
}
func (UnimplementedCmsServer) GetArticleDetail(context.Context, *GetArticleDetailReq) (*GetArticleDetailResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArticleDetail not implemented")
}
func (UnimplementedCmsServer) GetArticleList(context.Context, *GetArticleListReq) (*GetArticleListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArticleList not implemented")
}
func (UnimplementedCmsServer) LikeArticle(context.Context, *LikeArticleReq) (*LikeArticleResp, error) {
	return nil, status.Error(codes.Unimplemented, "method LikeArticle not implemented")
}
func (UnimplementedCmsServer) DeleteArticle(context.Context, *DeleteArticleReq) (*DeleteArticleResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteArticle not implemented")
}
func (UnimplementedCmsServer) CreateClearingData(context.Context, *CreateClearingDataReq) (*CreateClearingDataResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateClearingData not implemented")
}
func (UnimplementedCmsServer) UpdateClearingData(context.Context, *UpdateClearingDataReq) (*UpdateClearingDataResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateClearingData not implemented")
}
func (UnimplementedCmsServer) GetClearingDataDetail(context.Context, *GetClearingDataDetailReq) (*GetClearingDataDetailResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClearingDataDetail not implemented")
}
func (UnimplementedCmsServer) GetClearingDataList(context.Context, *GetClearingDataListReq) (*GetClearingDataListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClearingDataList not implemented")
}
func (UnimplementedCmsServer) DeleteClearingData(context.Context, *DeleteClearingDataReq) (*DeleteClearingDataResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteClearingData not implemented")
}
func (UnimplementedCmsServer) BatchCreateClearingData(context.Context, *BatchCreateClearingDataReq) (*BatchCreateClearingDataResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchCreateClearingData not implemented")
}
func (UnimplementedCmsServer) mustEmbedUnimplementedCmsServer() {}
func (UnimplementedCmsServer) testEmbeddedByValue()             {}

// UnsafeCmsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CmsServer will
// result in compilation errors.
type UnsafeCmsServer interface {
	mustEmbedUnimplementedCmsServer()
}

func RegisterCmsServer(s grpc.ServiceRegistrar, srv CmsServer) {
	// If the following call panics, it indicates UnimplementedCmsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Cms_ServiceDesc, srv)
}

func _Cms_CreateArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateArticleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).CreateArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cms_CreateArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).CreateArticle(ctx, req.(*CreateArticleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_UpdateArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateArticleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).UpdateArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cms_UpdateArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).UpdateArticle(ctx, req.(*UpdateArticleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_PublishArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishArticleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).PublishArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cms_PublishArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).PublishArticle(ctx, req.(*PublishArticleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_GetArticleDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticleDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).GetArticleDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cms_GetArticleDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).GetArticleDetail(ctx, req.(*GetArticleDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_GetArticleList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticleListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).GetArticleList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cms_GetArticleList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).GetArticleList(ctx, req.(*GetArticleListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_LikeArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeArticleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).LikeArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cms_LikeArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).LikeArticle(ctx, req.(*LikeArticleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_DeleteArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteArticleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).DeleteArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cms_DeleteArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).DeleteArticle(ctx, req.(*DeleteArticleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_CreateClearingData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClearingDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).CreateClearingData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cms_CreateClearingData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).CreateClearingData(ctx, req.(*CreateClearingDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_UpdateClearingData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateClearingDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).UpdateClearingData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cms_UpdateClearingData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).UpdateClearingData(ctx, req.(*UpdateClearingDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_GetClearingDataDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClearingDataDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).GetClearingDataDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cms_GetClearingDataDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).GetClearingDataDetail(ctx, req.(*GetClearingDataDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_GetClearingDataList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClearingDataListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).GetClearingDataList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cms_GetClearingDataList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).GetClearingDataList(ctx, req.(*GetClearingDataListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_DeleteClearingData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteClearingDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).DeleteClearingData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cms_DeleteClearingData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).DeleteClearingData(ctx, req.(*DeleteClearingDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_BatchCreateClearingData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCreateClearingDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).BatchCreateClearingData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cms_BatchCreateClearingData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).BatchCreateClearingData(ctx, req.(*BatchCreateClearingDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Cms_ServiceDesc is the grpc.ServiceDesc for Cms service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cms_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.cms",
	HandlerType: (*CmsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createArticle",
			Handler:    _Cms_CreateArticle_Handler,
		},
		{
			MethodName: "updateArticle",
			Handler:    _Cms_UpdateArticle_Handler,
		},
		{
			MethodName: "publishArticle",
			Handler:    _Cms_PublishArticle_Handler,
		},
		{
			MethodName: "getArticleDetail",
			Handler:    _Cms_GetArticleDetail_Handler,
		},
		{
			MethodName: "getArticleList",
			Handler:    _Cms_GetArticleList_Handler,
		},
		{
			MethodName: "likeArticle",
			Handler:    _Cms_LikeArticle_Handler,
		},
		{
			MethodName: "deleteArticle",
			Handler:    _Cms_DeleteArticle_Handler,
		},
		{
			MethodName: "createClearingData",
			Handler:    _Cms_CreateClearingData_Handler,
		},
		{
			MethodName: "updateClearingData",
			Handler:    _Cms_UpdateClearingData_Handler,
		},
		{
			MethodName: "getClearingDataDetail",
			Handler:    _Cms_GetClearingDataDetail_Handler,
		},
		{
			MethodName: "getClearingDataList",
			Handler:    _Cms_GetClearingDataList_Handler,
		},
		{
			MethodName: "deleteClearingData",
			Handler:    _Cms_DeleteClearingData_Handler,
		},
		{
			MethodName: "batchCreateClearingData",
			Handler:    _Cms_BatchCreateClearingData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cms.proto",
}
