// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	articleFieldNames          = builder.RawFieldNames(&Article{})
	articleRows                = strings.Join(articleFieldNames, ",")
	articleRowsExpectAutoSet   = strings.Join(stringx.Remove(articleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	articleRowsWithPlaceHolder = strings.Join(stringx.Remove(articleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheArticleIdPrefix = "cache:article:id:"
)

type (
	articleModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *Article) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Article, error)
		Update(ctx context.Context, session sqlx.Session, data *Article) error
		Delete(ctx context.Context, id int64) error
	}

	defaultArticleModel struct {
		sqlc.CachedConn
		table string
	}

	Article struct {
		Id          int64        `db:"id"`           // 文章id
		CreateTime  time.Time    `db:"create_time"`  // 创建时间
		UpdateTime  time.Time    `db:"update_time"`  // 更新时间
		DeleteTime  sql.NullTime `db:"delete_time"`  // 删除时间
		DelState    int64        `db:"del_state"`    // 删除状态 0:未删除 1:已删除
		Version     int64        `db:"version"`      // 版本号
		Title       string       `db:"title"`        // 文章标题
		Content     string       `db:"content"`      // 文章内容
		PublishTime time.Time    `db:"publish_time"` // 文章发布时间
		Category    string       `db:"category"`     // 文章分类
		LikeCount   int64        `db:"like_count"`   // 文章点赞数量
		AuthorId    int64        `db:"author_id"`    // 作者id
		CoverImage  string       `db:"cover_image"`  // 封面图片
		Status      int64        `db:"status"`       // 状态 0:草稿 1:已发布 2:已下架
	}
)

func newArticleModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultArticleModel {
	return &defaultArticleModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`article`",
	}
}

func (m *defaultArticleModel) Delete(ctx context.Context, id int64) error {
	articleIdKey := fmt.Sprintf("%s%v", cacheArticleIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, articleIdKey)
	return err
}

func (m *defaultArticleModel) FindOne(ctx context.Context, id int64) (*Article, error) {
	articleIdKey := fmt.Sprintf("%s%v", cacheArticleIdPrefix, id)
	var resp Article
	err := m.QueryRowCtx(ctx, &resp, articleIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", articleRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultArticleModel) Insert(ctx context.Context, session sqlx.Session, data *Article) (sql.Result, error) {
	articleIdKey := fmt.Sprintf("%s%v", cacheArticleIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, articleRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.Title, data.Content, data.PublishTime, data.Category, data.LikeCount, data.AuthorId, data.CoverImage, data.Status)
		}
		return conn.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.Title, data.Content, data.PublishTime, data.Category, data.LikeCount, data.AuthorId, data.CoverImage, data.Status)
	}, articleIdKey)
	return ret, err
}

func (m *defaultArticleModel) Update(ctx context.Context, session sqlx.Session, data *Article) error {
	articleIdKey := fmt.Sprintf("%s%v", cacheArticleIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, articleRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.Title, data.Content, data.PublishTime, data.Category, data.LikeCount, data.AuthorId, data.CoverImage, data.Status, data.Id)
		}
		return conn.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.Title, data.Content, data.PublishTime, data.Category, data.LikeCount, data.AuthorId, data.CoverImage, data.Status, data.Id)
	}, articleIdKey)
	return err
}

func (m *defaultArticleModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheArticleIdPrefix, primary)
}

func (m *defaultArticleModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", articleRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultArticleModel) tableName() string {
	return m.table
}
