// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tPriClearingDataGeneralYunnanFieldNames          = builder.RawFieldNames(&TPriClearingDataGeneralYunnan{})
	tPriClearingDataGeneralYunnanRows                = strings.Join(tPriClearingDataGeneralYunnanFieldNames, ",")
	tPriClearingDataGeneralYunnanRowsExpectAutoSet   = strings.Join(stringx.Remove(tPriClearingDataGeneralYunnanFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tPriClearingDataGeneralYunnanRowsWithPlaceHolder = strings.Join(stringx.Remove(tPriClearingDataGeneralYunnanFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTPriClearingDataGeneralYunnanIdPrefix                                      = "cache:tPriClearingDataGeneralYunnan:id:"
	cacheTPriClearingDataGeneralYunnanProvinceIdCompanyIdTargetDateTimeperiodPrefix = "cache:tPriClearingDataGeneralYunnan:provinceId:companyId:targetDate:timeperiod:"
)

type (
	tPriClearingDataGeneralYunnanModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *TPriClearingDataGeneralYunnan) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TPriClearingDataGeneralYunnan, error)
		FindOneByProvinceIdCompanyIdTargetDateTimeperiod(ctx context.Context, provinceId sql.NullInt64, companyId sql.NullString, targetDate sql.NullTime, timeperiod sql.NullString) (*TPriClearingDataGeneralYunnan, error)
		Update(ctx context.Context, session sqlx.Session, data *TPriClearingDataGeneralYunnan) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTPriClearingDataGeneralYunnanModel struct {
		sqlc.CachedConn
		table string
	}

	TPriClearingDataGeneralYunnan struct {
		Id                     int64     `db:"id"`                       // 主键
		ProvinceId             int64     `db:"province_id"`              // 省份id
		CompanyId              string    `db:"company_id"`               // 公司id
		CompanyName            string    `db:"company_name"`             // 公司名称
		UnitId                 string    `db:"unit_id"`                  // 单元或者机组单元id
		UnitName               string    `db:"unit_name"`                // 单元或者机组单元名称
		TargetDate             time.Time `db:"target_date"`              // 标的日期
		Timeperiod             string    `db:"timeperiod"`               // 时段
		DayaheadClearingEnergy float64   `db:"dayahead_clearing_energy"` // 日前出清电量（MWh）
		DayaheadClearingPrice  float64   `db:"dayahead_clearing_price"`  // 日前出清价格（元/MWh）
		RealtimeClearingEnergy float64   `db:"realtime_clearing_energy"` // 实时出清电量（MWh）
		RealtimeClearingPrice  float64   `db:"realtime_clearing_price"`  // 实时出清价格（元/MWh）
		CreateTime             time.Time `db:"create_time"`              // 创建时间
		UpdateTime             time.Time `db:"update_time"`              // 更新时间
		DayaheadBidPower       float64   `db:"dayahead_bid_power"`       // 日前中标出力(MW)
		RealtimeBidPower       float64   `db:"realtime_bid_power"`       // 实时中标出力(MW)
		ActualEnergy           float64   `db:"actual_energy"`            // 实际上网电量（MWh）
		ActualPower            float64   `db:"actual_power"`             // 实际发电出力（MW）
	}
)

func newTPriClearingDataGeneralYunnanModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTPriClearingDataGeneralYunnanModel {
	return &defaultTPriClearingDataGeneralYunnanModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_pri_clearing_data_general_yunnan`",
	}
}

func (m *defaultTPriClearingDataGeneralYunnanModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	tPriClearingDataGeneralYunnanIdKey := fmt.Sprintf("%s%v", cacheTPriClearingDataGeneralYunnanIdPrefix, id)
	tPriClearingDataGeneralYunnanProvinceIdCompanyIdTargetDateTimeperiodKey := fmt.Sprintf("%s%v:%v:%v:%v", cacheTPriClearingDataGeneralYunnanProvinceIdCompanyIdTargetDateTimeperiodPrefix, data.ProvinceId, data.CompanyId, data.TargetDate, data.Timeperiod)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tPriClearingDataGeneralYunnanIdKey, tPriClearingDataGeneralYunnanProvinceIdCompanyIdTargetDateTimeperiodKey)
	return err
}

func (m *defaultTPriClearingDataGeneralYunnanModel) FindOne(ctx context.Context, id int64) (*TPriClearingDataGeneralYunnan, error) {
	tPriClearingDataGeneralYunnanIdKey := fmt.Sprintf("%s%v", cacheTPriClearingDataGeneralYunnanIdPrefix, id)
	var resp TPriClearingDataGeneralYunnan
	err := m.QueryRowCtx(ctx, &resp, tPriClearingDataGeneralYunnanIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tPriClearingDataGeneralYunnanRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTPriClearingDataGeneralYunnanModel) FindOneByProvinceIdCompanyIdTargetDateTimeperiod(ctx context.Context, provinceId sql.NullInt64, companyId sql.NullString, targetDate sql.NullTime, timeperiod sql.NullString) (*TPriClearingDataGeneralYunnan, error) {
	tPriClearingDataGeneralYunnanProvinceIdCompanyIdTargetDateTimeperiodKey := fmt.Sprintf("%s%v:%v:%v:%v", cacheTPriClearingDataGeneralYunnanProvinceIdCompanyIdTargetDateTimeperiodPrefix, provinceId, companyId, targetDate, timeperiod)
	var resp TPriClearingDataGeneralYunnan
	err := m.QueryRowIndexCtx(ctx, &resp, tPriClearingDataGeneralYunnanProvinceIdCompanyIdTargetDateTimeperiodKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `province_id` = ? and `company_id` = ? and `target_date` = ? and `timeperiod` = ? limit 1", tPriClearingDataGeneralYunnanRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, provinceId, companyId, targetDate, timeperiod); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTPriClearingDataGeneralYunnanModel) Insert(ctx context.Context, session sqlx.Session, data *TPriClearingDataGeneralYunnan) (sql.Result, error) {
	tPriClearingDataGeneralYunnanIdKey := fmt.Sprintf("%s%v", cacheTPriClearingDataGeneralYunnanIdPrefix, data.Id)
	tPriClearingDataGeneralYunnanProvinceIdCompanyIdTargetDateTimeperiodKey := fmt.Sprintf("%s%v:%v:%v:%v", cacheTPriClearingDataGeneralYunnanProvinceIdCompanyIdTargetDateTimeperiodPrefix, data.ProvinceId, data.CompanyId, data.TargetDate, data.Timeperiod)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tPriClearingDataGeneralYunnanRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.ProvinceId, data.CompanyId, data.CompanyName, data.UnitId, data.UnitName, data.TargetDate, data.Timeperiod, data.DayaheadClearingEnergy, data.DayaheadClearingPrice, data.RealtimeClearingEnergy, data.RealtimeClearingPrice, data.DayaheadBidPower, data.RealtimeBidPower, data.ActualEnergy, data.ActualPower)
		}
		return conn.ExecCtx(ctx, query, data.ProvinceId, data.CompanyId, data.CompanyName, data.UnitId, data.UnitName, data.TargetDate, data.Timeperiod, data.DayaheadClearingEnergy, data.DayaheadClearingPrice, data.RealtimeClearingEnergy, data.RealtimeClearingPrice, data.DayaheadBidPower, data.RealtimeBidPower, data.ActualEnergy, data.ActualPower)
	}, tPriClearingDataGeneralYunnanIdKey, tPriClearingDataGeneralYunnanProvinceIdCompanyIdTargetDateTimeperiodKey)
	return ret, err
}

func (m *defaultTPriClearingDataGeneralYunnanModel) Update(ctx context.Context, session sqlx.Session, newData *TPriClearingDataGeneralYunnan) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	tPriClearingDataGeneralYunnanIdKey := fmt.Sprintf("%s%v", cacheTPriClearingDataGeneralYunnanIdPrefix, data.Id)
	tPriClearingDataGeneralYunnanProvinceIdCompanyIdTargetDateTimeperiodKey := fmt.Sprintf("%s%v:%v:%v:%v", cacheTPriClearingDataGeneralYunnanProvinceIdCompanyIdTargetDateTimeperiodPrefix, data.ProvinceId, data.CompanyId, data.TargetDate, data.Timeperiod)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tPriClearingDataGeneralYunnanRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, newData.ProvinceId, newData.CompanyId, newData.CompanyName, newData.UnitId, newData.UnitName, newData.TargetDate, newData.Timeperiod, newData.DayaheadClearingEnergy, newData.DayaheadClearingPrice, newData.RealtimeClearingEnergy, newData.RealtimeClearingPrice, newData.DayaheadBidPower, newData.RealtimeBidPower, newData.ActualEnergy, newData.ActualPower, newData.Id)
		}
		return conn.ExecCtx(ctx, query, newData.ProvinceId, newData.CompanyId, newData.CompanyName, newData.UnitId, newData.UnitName, newData.TargetDate, newData.Timeperiod, newData.DayaheadClearingEnergy, newData.DayaheadClearingPrice, newData.RealtimeClearingEnergy, newData.RealtimeClearingPrice, newData.DayaheadBidPower, newData.RealtimeBidPower, newData.ActualEnergy, newData.ActualPower, newData.Id)
	}, tPriClearingDataGeneralYunnanIdKey, tPriClearingDataGeneralYunnanProvinceIdCompanyIdTargetDateTimeperiodKey)
	return err
}

func (m *defaultTPriClearingDataGeneralYunnanModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTPriClearingDataGeneralYunnanIdPrefix, primary)
}

func (m *defaultTPriClearingDataGeneralYunnanModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tPriClearingDataGeneralYunnanRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTPriClearingDataGeneralYunnanModel) tableName() string {
	return m.table
}
