// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	article "looklook/app/cms/cmd/api/internal/handler/article"
	"looklook/app/cms/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取文章详情
				Method:  http.MethodPost,
				Path:    "/article/detail",
				Handler: article.ArticleDetailHandler(serverCtx),
			},
			{
				// 获取文章列表
				Method:  http.MethodPost,
				Path:    "/article/list",
				Handler: article.ArticleListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/cms/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建文章
				Method:  http.MethodPost,
				Path:    "/article/create",
				Handler: article.CreateArticleHandler(serverCtx),
			},
			{
				// 删除文章
				Method:  http.MethodPost,
				Path:    "/article/delete",
				Handler: article.DeleteArticleHandler(serverCtx),
			},
			{
				// 点赞文章
				Method:  http.MethodPost,
				Path:    "/article/like",
				Handler: article.LikeArticleHandler(serverCtx),
			},
			{
				// 发布文章
				Method:  http.MethodPost,
				Path:    "/article/publish",
				Handler: article.PublishArticleHandler(serverCtx),
			},
			{
				// 更新文章
				Method:  http.MethodPost,
				Path:    "/article/update",
				Handler: article.UpdateArticleHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/cms/v1"),
	)
}
